DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS CONDITION;
DROP TABLE IF EXISTS SIZE;
DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS MESSAGE;
DROP TABLE IF EXISTS WISHLIST;
DROP TABLE IF EXISTS CART;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS ITEM_CATEGORY;
DROP TABLE IF EXISTS IMAGE;

-- Create USER table
CREATE TABLE USER (
    UserId INTEGER NOT NULL PRIMARY KEY,
    Name TEXT NOT NULL,
    Username TEXT NOT NULL,
    Password TEXT NOT NULL,
    Email TEXT NOT NULL,
    Admin BOOLEAN DEFAULT FALSE
);

-- Create CONDITION table
CREATE TABLE CONDITION (
    ConditionId INTEGER PRIMARY KEY,
    ConditionVal TEXT NOT NULL
);

-- Create SIZE table
CREATE TABLE SIZE (
    SizeId INTEGER PRIMARY KEY,
    SizeVal TEXT NOT NULL
);

-- Create ITEM table
CREATE TABLE ITEM (
    ItemId INTEGER NOT NULL PRIMARY KEY,
    UserId INTEGER NOT NULL,
    Price FLOAT NOT NULL,
    Description TEXT NOT NULL,
    ConditionId INTEGER NOT NULL,
    SizeId INTEGER NOT NULL,
    Brand TEXT,
    CONSTRAINT PriceConstraint CHECK (Price > 0),
    FOREIGN KEY (UserId) REFERENCES USER (UserId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ConditionId) REFERENCES CONDITION (ConditionId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (SizeId) REFERENCES SIZE (SizeId) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create MESSAGE table
CREATE TABLE MESSAGE (
    MessageId INTEGER NOT NULL PRIMARY KEY,
    AuthorId INTEGER NOT NULL,
    ReceiverId INTEGER NOT NULL,
    Content TEXT NOT NULL,
    Timestamp DATETIME NOT NULL,
    FOREIGN KEY (AuthorId) REFERENCES USER (UserId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ReceiverId) REFERENCES USER (UserId) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create WISHLIST table
CREATE TABLE WISHLIST (
    UserId INTEGER NOT NULL,
    ItemId INTEGER NOT NULL,
    FOREIGN KEY (UserId) REFERENCES USER (UserId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ItemId) REFERENCES ITEM (ItemId) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PK_Wishlist PRIMARY KEY (UserId, ItemId)
);

-- Create CART table
CREATE TABLE CART (
    UserId INTEGER NOT NULL,
    ItemId INTEGER NOT NULL,
    FOREIGN KEY (UserId) REFERENCES USER (UserId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ItemId) REFERENCES ITEM (ItemId) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PK_Cart PRIMARY KEY (UserId, ItemId)
);

-- Create CATEGORY table
CREATE TABLE CATEGORY (
    CategoryName TEXT NOT NULL PRIMARY KEY
);

CREATE TABLE ITEM_CATEGORY (
    CategoryId INTEGER NOT NULL,
    ItemId INTEGER NOT NULL,
    FOREIGN KEY (CategoryId) REFERENCES CATEGORY (CategoryId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ItemId) REFERENCES ITEM (ItemId) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PK_ItemCategory PRIMARY KEY (CategoryId, ItemId)
);

CREATE TABLE IMAGE (
    Path TEXT NOT NULL PRIMARY KEY,
    ItemId INTEGER NOT NULL,
    FOREIGN KEY (ItemId) REFERENCES ITEM (ItemId) ON DELETE CASCADE ON UPDATE CASCADE
);
